version: "3.9"

services:
  db:
    image: postgres:15
    container_name: iaemp-db
    environment:
      POSTGRES_DB: iaemp_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    container_name: iaemp-backend
    build:
      context: ./iaemp-backend
      dockerfile: Dockerfile
    env_file:
      - ./iaemp-backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    container_name: iaemp-nginx
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./iaemp-frontend:/usr/share/nginx/html:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro

volumes:
  pgdata:
