apiVersion: apps/v1
kind: Deployment
metadata:
  name: iaemp-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iaemp-postgres
  template:
    metadata:
      labels:
        app: iaemp-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: iaemp_db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
